// FILE: src/categoriesAndLocations.js

export const LOCATION_OPTIONS = [
  "Όλες οι πόλεις",
  "Αθήνα",
  "Θεσσαλονίκη",
  "Πάτρα",
  "Ηράκλειο",
  "Λάρισα",
  "Βόλος",
  "Ιωάννινα",
  "Καβάλα",
  "Σέρρες",
  "Χανιά",
  "Αχαρνές",
];

export const TRAINER_CATEGORIES = [
  {
    value: "personal_trainer",
    label: "Προσωπικός Εκπαιδευτής",
    iconKey: "dumbbell",
    specialties: [
      "Απώλεια λίπους",
      "Μυϊκή ενδυνάμωση",
      "Προπόνηση με βάρη",
      "Σωματική μεταμόρφωση",
      "Προετοιμασία αγώνων/διαγωνισμών",
      "Προπόνηση αρχαρίων",
      "Προπόνηση τρίτης ηλικίας",
      "Προπόνηση εγκύων",
    ],
  },
  {
    value: "group_fitness_instructor",
    label: "Εκπαιδευτής Ομαδικών Προγραμμάτων",
    iconKey: "users",
    specialties: [
      "HIIT υψηλής έντασης",
      "Bootcamp",
      "Λειτουργική προπόνηση (Functional)",
      "TRX",
      "Κυκλική προπόνηση (Circuit)",
      "Αερόβια προπόνηση (Cardio)",
      "Ομαδικά γυναικών",
    ],
  },
  {
    value: "pilates_instructor",
    label: "Εκπαιδευτής Pilates",
    iconKey: "pilates",
    specialties: [
      "Mat Pilates",
      "Reformer Pilates",
      "Προγεννητικό & Μεταγεννητικό",
      "Στάση σώματος / Ενδυνάμωση Core",
      "Pilates για αποκατάσταση",
    ],
  },
  {
    value: "yoga_instructor",
    label: "Εκπαιδευτής Yoga",
    iconKey: "yoga",
    specialties: [
      "Hatha Yoga",
      "Vinyasa Flow",
      "Power Yoga",
      "Yin Yoga",
      "Prenatal Yoga",
      "Mindfulness & Αναπνοές",
    ],
  },
  {
    value: "nutritionist",
    label: "Διατροφολόγος",
    iconKey: "apple",
    specialties: [
      "Απώλεια βάρους",
      "Αύξηση μυϊκής μάζας",
      "Vegan / Χορτοφαγική διατροφή",
      "Διατροφική υποστήριξη αθλητών",
      "Προγράμματα διατροφής με delivery",
      "Εντερική υγεία & δυσανεξίες",
    ],
  },
  {
    value: "online_coach",
    label: "Online Προπονητής",
    iconKey: "laptop",
    specialties: [
      "Απομακρυσμένο 1-on-1 coaching",
      "Προγράμματα PDF / Video",
      "Συνδυασμός Διατροφής + Προπόνησης",
      "Ζωντανά μαθήματα μέσω Zoom",
      "Coaching υπευθυνότητας (accountability)",
    ],
  },
  {
    value: "strength_conditioning",
    label: "Προπονητής Δύναμης & Φυσικής Κατάστασης",
    iconKey: "strength",
    specialties: [
      "Ανάπτυξη αθλητών",
      "Αθλητικές επιδόσεις",
      "Ολυμπιακές άρσεις",
      "Πλειομετρικές ασκήσεις",
      "Ανθεκτικότητα σε τραυματισμούς",
    ],
  },
  {
    value: "calisthenics",
    label: "Εκπαιδευτής Calisthenics",
    iconKey: "calisthenics",
    specialties: [
      "Στατική δύναμη",
      "Δυναμικές δεξιότητες (Muscle-up, Planche)",
      "Ευκινησία & Έλεγχος",
      "Street workout",
      "Προπόνηση σε κρίκους",
    ],
  },
  {
    value: "crossfit_coach",
    label: "Προπονητής CrossFit",
    iconKey: "crossfit",
    specialties: [
      "Καθημερινός προγραμματισμός (WODs)",
      "Ολυμπιακές άρσεις",
      "Προετοιμασία για αγώνες",
      "Γυμναστικές δεξιότητες",
      "Metcons",
    ],
  },
  {
    value: "boxing_kickboxing",
    label: "Προπονητής Πυγμαχίας / Kickboxing",
    iconKey: "boxing",
    specialties: [
      "Cardio boxing",
      "Sparring",
      "Ασκήσεις με σάκο",
      "Βελτίωση τεχνικής",
      "Παιδιά / Αρχάριοι",
    ],
  },
  {
    value: "martial_arts",
    label: "Εκπαιδευτής Πολεμικών Τεχνών",
    iconKey: "martial",
    specialties: [
      "Brazilian Jiu-Jitsu (BJJ)",
      "Muay Thai",
      "Καράτε",
      "Krav Maga",
      "Αυτοάμυνα",
      "Taekwondo",
      "Προετοιμασία MMA",
    ],
  },
  {
    value: "dance_fitness",
    label: "Εκπαιδευτής Χορευτικής Γυμναστικής",
    iconKey: "dance",
    specialties: [
      "Zumba",
      "Latin dance fitness",
      "Afrobeat / Hip hop cardio",
      "Τόνωση γυναικών",
      "Χορός για ηλικιωμένους",
    ],
  },
  {
    value: "running_coach",
    label: "Προπονητής Τρεξίματος",
    iconKey: "running",
    specialties: [
      "Μαραθώνιος / Ημιμαραθώνιος",
      "Προπόνηση sprint",
      "Διόρθωση τεχνικής τρεξίματος",
      "Προπόνηση αντοχής",
      "Τρέξιμο για αρχάριους",
    ],
  },
  {
    value: "physiotherapist",
    label: "Φυσικοθεραπευτής",
    iconKey: "physio",
    specialties: [
      "Αποκατάσταση τραυματισμών",
      "Manual therapy",
      "Κινησιοθεραπεία",
      "Χρόνιοι πόνοι",
      "Αθλητική αποκατάσταση",
    ],
  },
  {
    value: "rehab_prevention",
    label: "Ειδικός Αποκατάστασης / Πρόληψης Τραυματισμών",
    iconKey: "rehab",
    specialties: [
      "Εργονομική ενδυνάμωση",
      "Διόρθωση κινητικών προτύπων",
      "Ισορροπία & σταθερότητα",
      "Επανένταξη μετά από χειρουργείο",
    ],
  },
  {
    value: "wellness_life_coach",
    label: "Προπονητής Ευεξίας & Ζωής",
    iconKey: "wellness",
    specialties: [
      "Διαχείριση άγχους",
      "Coaching συνηθειών & χρόνου",
      "Ψυχική ανθεκτικότητα",
      "Αποκατάσταση από burnout",
      "Ολιστικός καθορισμός στόχων",
    ],
  },
  {
    value: "performance_psych",
    label: "Προπονητής Απόδοσης / Αθλητικός Ψυχολόγος",
    iconKey: "psychology",
    specialties: [
      "Εκπαίδευση συγκέντρωσης",
      "Ψυχολογία ημέρας αγώνα",
      "Τεχνικές οπτικοποίησης",
      "Αγωνιστικό mindset",
      "Κατάσταση ροής (flow state) coaching",
    ],
  },
];